packages:
  - studio
  - web
  - packages/*

allowBuilds:
  esbuild: true
  core-js-pure: false

minimumReleaseAgeExclude:
  - '@sanity/access-ui@6.14.0'
  - '@sanity/diff@6.14.0'
  - '@sanity/mutator@6.14.0'
  - '@sanity/schema@6.14.0'
  - '@sanity/types@6.14.0'
  - '@sanity/util@6.14.0'
  - '@sanity/validation@6.14.0'
  - '@sanity/vision@6.14.0'
  - sanity@6.14.0
  - '@maplibre/maplibre-gl-style-spec@26.4.4'
  - maplibre-gl@6.10.0
